library(dplyr)
mecha <-read.csv('MechaCar_mpg.csv')
head(mecha)
lr_model <-lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data = mecha)
summary(lr_model)
sus <-read.csv("Suspension_Coil.csv")
head(sus)
total_summary <- sus %>%summarize(Mean = mean(PSI),Median = median(PSI), Variance = sd(PSI)**2, SD = sd(PSI))
lot_summary <- sus%>%group_by(Manufacturing_Lot)%>%summarize(Mean = mean(PSI),Median = median(PSI), Variance = sd(PSI)**2, SD = sd(PSI))
t.test(sus$PSI,mu=1500)
t.test(subset(sus,Manufacturing_Lot == "Lot1")$PSI,mu=1500)
t.test(subset(sus,Manufacturing_Lot == "Lot2")$PSI,mu=1500)
t.test(subset(sus,Manufacturing_Lot == "Lot3")$PSI,mu=1500)
